model_name: fully-connected-network
batch_size: 512
epochs: 1000
features:
  - 100
  - 102
  - 105

optimizer: SGD
optimizer_params:
  - lr
lr: 0.01

scheduler_factor: 0.5
scheduler_patience: 50

model_params:
  - hidden_layer_sizes
  - activation
  - dropouts
hidden_layer_sizes:
  - 32
activation: ReLU
dropouts:
  - 0
