name: random_forest
method: grid
metric:
  goal: maximize
  name: gain

parameters:
  model_type:
    value: RandomForest
  features:
    values:
      - [102, 103, 105]
      - [0, 102, 105]
      - [101, 102, 103]
      - [0, 100, 102, 105]
      - [101, 102, 103, 105]
      - [0, 101, 102, 105]
      - [0, 101, 102, 103]
      - [100, 101, 102, 105]
      - [0, 100, 102, 105]
      - [0, 102, 103, 105]
      - [0, 101, 102, 103, 105]
      - [100, 101, 102, 103, 105]
  model_params:
    value:
      - n_estimators
      - max_depth
  n_estimators:
    values:
        - 5
        - 10
        - 20
        - 50
        - 100
        - 200
  max_depth:
    values:
      - null
      - 1
      - 2
      - 3
      - 4
      - 5
  test_size:
    value: 0.5
  repeat:
    value: 5
